legastero/stanza

lib/plugins/sasl.js
Consider the following scenario:
1) The client connects to the server.
2) The server advertises 'sasl' feature with SCRAM-SHA-1 mechanism.
3) The client calls custom `self.getCredentials()` callback (which shows a user prompt).
4) User never provides any credentials.
5) The client is disconnected by the server by timeout.
6) (The same) client reconnects to the server.
7) `client.getCredentials()` is called again, showing the user prompt again.
8) User finally provides the credentials in reasonable time (which are then stored, passed to the callback and also returned immediately in subsequent `client.getCredentials()` runs).
9) The client sends `sasl:auth`, receives `sasl:challenge` and replies with a **double** `sasl:response` with different nonces.
10) The server closes the connection …
=> Fixed duplicate SASL callback response after reconnect

lib/client.js
I'm working on a solution for react-native, and for that I am build my "own" transport plugin. It would make my life a lot easier if the other transports isn't loaded, when I'm using mine.
Also:
- `transInfo.url` was never used.
This PR does not require any tests, as these changes were regarding connect, and that already has integration-test (still passing).
=> Don't load transports, until they are used.

lib/transports/websocket.js
I'm seeing intermittent errors in the console because we are trying to close a websocket that doesn't exist.
=> Ensure websocket exists before trying to close it

lib/plugins/jingle.js
uses the newer .urls syntax for stun and turn servers.
Yes, it can be a string instead of an array!
=> xep-0215: use urls syntax

lib/plugins/roster.js
Default value for `cb` prevented Promise.catch, so even if there was an error it still goes into Promise.then with undefined, and as there are if statements to check if callback was provided it will not crash and promise will eat `throw err` for users that didn't process the result.
=> Fix client.getRoster to use as Promise func

lib/transports/bosh.js
Header is required for react-native. [this issue](https://github.com/MattFoley/react-native-stanza-demo/issues/1)
=> Heading for bosh added

lib/transports/bosh.js
attempt to fix bosh connexion to ejabberd with stanza.io
According to [XEP-026](http://xmpp.org/extensions/xep-0206.html)
> Upon receiving the <success/> element, the client MUST then ask the connection manager to restart the stream by sending a "restart request"
Unfortunately an empty request is sent after authentication but before xmpp:restart, because of a race condition. Checking if authenticated before sending a new request, prevents race condition from occurring.
related to legastero/stanza.io#186
=> Bosh - prevent race condition from happening

docs/Supported_XEPs.md
References xep was listed as 352 instead of 372.
=> Fix typo in support xeps list

lib/plugins/jingle.js
There was a period instead of a colon in the urn:xmpp:jingle:transports:dtls-sctp:1 feature string
=> Fix typo in urn:xmpp:jingle:transports:dtls-sctp:1

lib/plugins/mam.js, package.json
Not sure if we're ready for this? Or if there's a way to support both mam:0 and mam:2 (I doubt it?) but we've been using this for a while and figured I should try and upstream.
Depends on https://github.com/otalk/jxt-xmpp/pull/21 (note the commit in this PR that points jxt-xmpp to a fork, which shall need to be removed before merging).
=> MAM2 support

docs/Reference.md, lib/transports/websocket.js, package.json
RE: https://github.com/legastero/stanza.io/issues/242
There are two commits here:
The first allows passing a `wsOptions` parameter to the constructor, which in turn will be passed to the constructor for the WebSocket transport.  For faye-websocket-node, this enables specifying the SNI server name via a `tls` parameter.
The second bumps the faye-websocket dependency from 0.10 to 0.11.  The faye-websocket 0.11 release included a change to set the server name parameter by default, so the explicit use of this `wsOptions` parameter should not be necessary for the most common use case.
Without one of these commits or the other, it is not possible to use stanza.io in a node.js XMPP client using the WebSocket transport with a TLS front-end that depends on SNI.  This includes Amazon's Application …
=> Improvements to the WebSocket transport for handling TLS endpoints employing SNI

lib/transports/bosh.js
Fixes #262 
I had to chain the promises correctly so that the error is always caught. There was no need to emit a new event as the existing `stream:error` is sufficient :man_dancing:
=> Fix Uncaught error on timeout (bosh)

docs/Reference.md, lib/plugins/index.js, lib/plugins/push.js
Add two new functions to `client`: `enableNotifications` and
`disableNotifications` for clients to send the required stanzas for
enabling and disabling push notifications.
=> feat(push): add support for XEP-0357: Push Notifications

src/plugins/markers.js
We found out that emitting only the message ID forces the application to do messages' lookup actions that can be avoided by emitting the full msg on chat marker events, simplifying `stanza.io` users' code.
What do you think of this change?
BREAKING CHANGE: full object now emitted instead of a plain message ID
=> refactor: emit full message on Chat Markers events

docs/Supported_XEPs.md
I've noticed that reference to XEP-0357 is missing.
Feature merged in this PR #274
=> Add support for XEP-0357

src/plugins/push.js
I encountered a problem using the push notifications feature with an ejabberd server.
The client was sending:
```xml
<iq xmlns="jabber:client" type="set" id="30084eb7-52a6-4862-ac8f-c4893dd51597">
<enable xmlns="urn:xmpp:push:0" jid="client-1@push.localhost" node="test-42">
<x xmlns="jabber:x:data">
<field var="FORM_TYPE"><value>http://jabber.org/protocol/pubsub#publish-options</value></field>
<field var="custom-field"><value>custom-value</value></field>
</x>
</enable>
</iq>
```
The ejabberd server was replying:
```xml
<iq xmlns="jabber:client" xml:lang="en" to="test@localhost/chrome-stanza-04" from="test@localhost" type="error" id="30084eb7-52a6-4862-ac8f-c4893dd51597">
...
<error code="400" type="modify">
<bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" />
<text xml:lang="en" …
```
=> Fix: Push Notifcation, type field to form while enabling

docs/Reference.md, src/plugins/muc.js
The name was a bit misguiding as some events had nothing to do with changes in
muc affiliation. New name makes reference of other muc related events that are
not included in a specific element. Some example of possible events are:
```
{
"muc": {
"codes": [
"104",
"170",
"172"
]
},
"room": "f2c06530-1831-11e9-a5f0-b7c86edf572e@conference.example.com",
"to": "alice@example.com/VopfXx38"
}
```
```
{
"muc": {
"actor": {
"jid": ""
},
"affiliation": "member",
"jid": "bob@example.com",
"reason": "Invited by alice@example.com/VopfXx38"
},
"room": "f2c06530-1831-11e9-a5f0-b7c86edf572e@conference.example.com",
"to": "alice@example.com/VopfXx38"
}
```
=> Change muc:affiliation event name to muc:other and include the "to" field

src/client.js, src/plugins/markers.js
- Export method to mark a message as received. This is needed because messages are not always marked as received automatically (e.g.: when retrieving older messages in a muc).
- Send mark messages with type chat/groupchat and include an empty body in them to force MAM to archive them.
- Don't emit chat/groupchat event when the message includes a received or displayed mark.
=> improve chat markers

src/protocol/stanzas/hints.js
Current code removes every child of a different namespace while if I'm not wrong the expected behaviour is removing current children of the message processing hints namespace.
=> fix problem with message processing hints

docs/Reference.md, src/plugins/index.js, src/plugins/upload.js, src/protocol/index.js, src/protocol/stanzas/upload.js
This change adds JXT types and client methods for requesting HTTP upload slots.
Closes #296.
I've tested the change locally on my client and it looks fine but I'm open for suggestions about method names & style.
Thank you!
=> Add support for HTTP File Upload (XEP-0363)

package.json, webpack.config.js
Webpack bundling entry point path is already compiled by typescript and then bundled by rollup. Using typescript with existing configuration is transforming esm to cjs preventing tree shaking to occur while bundling the dependencies.
=> Stop transpiling to CJS modules before webpack bundling

docs/Configuring.md
Markdown isn't processed in html blocks.
=> Replaces markdown tag in html block

src/Client.ts, src/index.ts
The annotation for sendMessage is out of step with the behaviour, I've assumed that the preferred outcome is to return the message id.
=> sendMessage() returns a string, the message id

src/lib/sasl/index.ts, test/sasl/factory.ts
Our system supports ANONYMOUS and PLAIN. It took me some time to figure out why it was using the wrong mechanism. It's because when the ANONYMOUS mechanism gets registered ([here](https://github.com/legastero/stanza/blob/c16c01ed266f9f47ee68ff35a1e0b42a760a4466/src/Client.ts#L59)), it has a priority of `0` which was getting changed to `mechanisms.length`, making it a higher priority than PLAIN. Since `priority` is a required param for the register method, I didn't see the point of defaulting it.
=> fix sasl priorities from getting messed up

README.md
In my opinion, it's a very important advantage of StanzaJS compared to the other JS libraries and should be mentioned somewhere.
Currently a Google search `xmpp library typescript` doesn't return this library as a search result. I hope this PR would change it.
Suggested action items for maintainers:
Probably it would also be useful to provide an example for ts, but most of the examples are html+js, and the current echo client doesn't require any type annotations due to type inference. I could modify the echo client example to make some use of types, but this would be artificial.
Please tag this PR as `hacktoberfest-accepted` if you think it's a useful PR. Thanks ;)
=> Mention TypeScript support in the README

src/Client.ts
The reconnectTimer must be cleared on disconnect or otherwise the connection will be restarted in a case where disconnect is called after reconnect timer was scheduled.
=> fix(Client): clear reconnectTimer

src/plugins/muc.ts
There's no need to rejoin any already joined MUC rooms upon session resume, because the user should still be inside those rooms. That's entire reason for doing SM resume - to avoid having to rebuild the session's state when connection drops.
=> fix(muc): do not rejoin rooms on stream:management:resumed

src/plugins/connection.ts, src/transports/websocket.ts
...and follow up with the --transport-disconnected event.
In case keep alive timeout occurs it calls disconnect, but that
has no real effect without closing the websocket.
@legastero thanks for merging my other PRs! I really like the library, especially it's nice and clean API.
To give some more context on this case. I have enabled keep alives and was trying to rely on them to detect a dead Webocket(dead TCP) connection. This can be tested by having keep alives enabled and then disconnecting ethernet cable and switching over to wifi for example (on Mac Catalina). Probably it could reproduce on some OSes when switching VPNs etc.
Without this change the problem is that even though the timeout error is logged the connection is not really closed. It takes quite more time for the 'on ended' …
=> fix(websocket): explicitly close WebSocket on unclean disconnect

src/index.ts, src/transports/bosh.ts
I was using version 8.4.13 of stanza. I had to update the Stanza but it acted like it hadn't behaved before. The messages I sent were waiting for the previous request to finish (for Openfire). Therefore, I looked at the differences between them and realized that the "hold" value was "2" in the bosh request. However, it used to be "1". And, when I set this to 1, it was worked.
At the same time, when I sent more than one presence package at the same time, it generates a "bosh" request. However, it now creates a separate bosh request for each presence. I'm asking because I can't understand how to fix this. Thank you.
=> "maxHoldOpen" has been made modifiable.

src/plugins/messaging.ts
Currently the chatMarkers config not only disables the automatic sending of markers but even manual marker sending.
With this change the automatic received marker is still blocked if set to false but you can still manually send it.
=> adjust chatMarkers config effect

.eslintrc.js, src/Client.ts, src/plugins/messaging.ts, src/plugins/pubsub.ts, test/jxt/sanitizer.ts
Do not reuse the ID from the message we're acknowledging its reception
or marker status.
The outgoing message must use a new ID.
=> fix: use new random message ID 

package.json
the async library's `priorityQueue` uses `setImmediate()` in the browser. Set immediate doesn't actually exist in browsers and so it falls back to `setTimeout(fn, 0)`. We noticed that when trying to do webrtc our sending of ice candidates was getting throttled if the tab/browser wasn't visible. We were able to track the problem down to the async library and get a fix pr'd and released. Here more information on how the browser throttling works: https://developer.chrome.com/blog/timer-throttling-in-chrome-88/
This pr just bump async to use the latest version which uses `queueMicrotask()` instead of `setTimeout()` for `setImmediate()`.
=> bump async to fix browser throttling

src/plugins/muc.ts, test/muc/messages.ts
XEP-0045 "Multi-User Chat" section 7.2.15 "Room Subject" states:
> Note: In accordance with the core definition of XML stanzas, any message can contain a
> <subject/> element; only a message that contains a <subject/> but no <body/> element
> shall be considered a subject change for MUC purposes.
See: https://xmpp.org/extensions/xep-0045.html#enter-subject
Stanza currently emits the 'muc:topic' event for any groupchat message that has a subject.
This should only occur for stanzas that have _no_ body.
This commit adds a test and a functional change to this effect.
=> fix(muc): message with body and subject isn't subject change

src/helpers/StreamManagement.ts, test/stream-management.ts
This merge request is fixing Stream management bug which causes getting duplicated stanzas after resuming session.
If session was resumed - stanza resume was sent with h set to last h value from previous session - counter for handled stanzas is set to 0. Because of this reset, xmpp server is sending every stanza until client reach the h number from last session.
Example: before disconnection, on the client side, h is 20, and on the server side, h is also set to 20. The client loses connection with the server, after which it is restored. Resume stanza is sent with h of 20, then h is reset to 0. The server then sends 20 stanzas to the client, which are marked as delayed.
=> Reset handled counter only for enable stanzas

src/helpers/StreamManagement.ts, test/stream-management.ts
Consider this exchange between a stanza.io client, and a server. It shows the client enabling stream management, as described in [section 3 of XEP-0198](https://xmpp.org/extensions/xep-0198.html#enable).
raw:outgoing: `<enable xmlns="urn:xmpp:sm:3" resume="1"/>`
raw:incoming: `<enabled xmlns="urn:xmpp:sm:3"/>`
Here, the client indicates that wants to be allowed to resume a previous setting, by including a boolean 'resume' attribute.
When the server allows for Ack-ing functionality, but does not support then Resumption functionality, it is allowed to respond with an `<enabled>` element that does not include the `resume` attribute (or possibly with a falsy attribute value).
Stanza.io should, in this case, not mark the stream to be resumable, but, prior to this commit, it does.
This commit …
=> Must evaluate 'resume' in SM 'enabled' response

src/jingle/sdp/Protocol.ts
current source is not compiling. This fixes the compile
=> fix compile error

.github/workflows/ci.yaml
Minor improvements:
- bumps version numbers of Github Actions that are used to implement the workflow
- workflow now runs on PR requests too
- adds nodejs 18 (which is a newer LTS release)
- always builds against the latest version of each LTS release
=> Improvements for the GitHub CI workflow

src/protocol/rfc6121.ts
On the RosterItem type:
* the pending (ask) property is missing
* approved property should be preApproved
see also:
https://github.com/legastero/stanza/blob/f20155b05d4b94d454b42ce1739caa89442ce293/src/protocol/rfc6121.ts#L110-L111
=> fix rosteritem definition
