legastero/stanza

README.md
When pulling this project for the first time, I couldn't get `make` to run without also including this step.
=> Update README.md Getting Started steps.

lib/client.js, package.json
Hi, I added another one lib for token authorization. Now you can add token and username keys into credentials like this:
credentials: {
host: ' ',
token: ' ',
username: ' '
}
and it will work. I've tested it in my application. And you should update your documentation if everything is ok
=> new SASL mechanism

docs/Reference.md
I added couple of examples for:
getDiscoItems(),
searchHistory(),
enableCarbons()
=> Documented some APIs

docs/Reference.md
Updated docs with some examples.
=> Docs Update

lib/transports/websocket.js
=> Fix this scope

docs/Supported_XEPs.md, lib/plugins/references.js
See also https://github.com/otalk/jxt-xmpp/pull/19
=> Add support for references (xep-0372)

docs/Reference.md
=> Updated Reference docs

docs/Reference.md, docs/Supported_XEPs.md, lib/plugins/index.js, lib/plugins/markers.js, package.json
This is my attempt to support Chat Markers in stanza.io.  Will do some more testing, but this seems to be working in our environment.
Feedback will be welcomed :)
=> feat: add support for XEP-0333

lib/transports/bosh.js
Request and response have been known by means of the RID. I added separate RID to both.
=> raw:incoming:RID and raw:outgoing:RID added for bosh.

src/plugins/pubsub.js
- id attribute in <item/> element not getting set
- this is also affecting getAvatar in avatar plugin
=> fix(pubsub): id attribute in item element not set

docs/Reference.md, src/plugins/muc.js
The event is emitted when a messages informing about changes in affiliation is received
=> feat: add muc:affiliation event

package.json, scripts/build.js
=> fix build on Windows

demo.html, src/client.js, src/sm.js
This is work in progress to figure out how this api should work.
=> Add handlers to allow loading/caching stream management state

docs/Create_Plugin.md
stanza/index.ts exports JXT, not jxt.
=> jxt to JXT

src/protocol/xep0054.ts
=> XEP-0054 add vcard definitions

examples/jingle-demo.html
Hi @legastero!
I played around with the jingle demo and added the ability to share screen. Tested calling Conversations 2.8.3 (beta) and looks pretty nice :)
=> jingle-demo: Add screensharing capability

src/plugins/connection.ts
If keep alives were enabled, re-enable them after session resume or session restart (session:end session:start).
=> ref(connection): auto manage keep alive

src/plugins/jingle.ts
Added the Typescript Typings for the 'jingle:accepted' event.
=> Add Typings for Jingle Session Accepted event.

docs/Using_PubSub.md
Add samples of creating and deleting a node.
=> Introduce samples of creating and deleting a node

src/transports/websocket.ts
In case of bad network or high packet loss the response for the close header won't be received. This causes the transport instance to never fully disconnect.
I propose this timeout as a fallback in case a response wasn't received after 1 second.
1. Enable a high packet loss or simulate a bad network condition
2. Trigger the `sendStreamError`
3. The first flow of the `disconnect` will be triggered but the close response won't ever be received
=> Add fallback timeout for WebSocket disconnect
